import { describe, it, expect } from 'vitest'
import {
  formatTaskCommitMessage,
  formatTaskPRTitle,
  formatTaskPRBody,
  validateTaskSync,
} from '@/lib/git/task-git-sync'
import { taskBranchName } from '@/lib/git/gitea-client'

/**
 * #356 GIT-3 — Task→Git sync tests. These test the PURE helpers (commit message
 * formatting, PR title/body formatting, validation). The network calls (branch
 * creation, file push, PR creation) are integration-tested against a live Gitea
 * when GITEA_* are configured.
 *
 * Target: 80%+ coverage on the pure logic.
 */

describe('task-git-sync (#356 GIT-3)', () => {
  describe('taskBranchName (pure, from gitea-client)', () => {
    it('formats a valid task branch name', () => {
      expect(taskBranchName('task-123')).toBe('task/task-123')
    })

    it('sanitizes special characters in taskId portion', () => {
      const name = taskBranchName('task/with:special@chars')
      expect(name).toBe('task/task-with-special-chars')
      // The 'task/' prefix is expected; only the taskId part should be sanitized
      const taskIdPart = name.slice(5) // remove 'task/'
      expect(taskIdPart).not.toMatch(/[:@]/)
    })

    it('lowercases the taskId', () => {
      expect(taskBranchName('TASK-ABC')).toBe('task/task-abc')
    })

    it('truncates long taskIds', () => {
      const longId = 'a'.repeat(100)
      const name = taskBranchName(longId)
      expect(name.length).toBeLessThanOrEqual(55) // 'task/' + 50 chars
    })

    it('returns empty string for empty taskId', () => {
      expect(taskBranchName('')).toBe('')
      expect(taskBranchName('   ')).toBe('')
    })

    it('is deterministic', () => {
      expect(taskBranchName('x')).toBe(taskBranchName('x'))
    })
  })

  describe('formatTaskCommitMessage (pure)', () => {
    it('formats message with taskId and title', () => {
      const msg = formatTaskCommitMessage('task-123', 'Add login button')
      expect(msg).toBe('Task task-123: Add login button')
    })

    it('formats message with taskId only', () => {
      const msg = formatTaskCommitMessage('task-123')
      expect(msg).toBe('Task task-123')
    })

    it('formats message with title only', () => {
      const msg = formatTaskCommitMessage('', 'Add login button')
      expect(msg).toBe('Add login button')
    })

    it('returns fallback for empty inputs', () => {
      const msg = formatTaskCommitMessage('', '')
      expect(msg).toBe('Task commit')
    })

    it('truncates long taskIds', () => {
      const longId = 'a'.repeat(100)
      const msg = formatTaskCommitMessage(longId)
      expect(msg.length).toBeLessThan(60) // 'Task ' + 50 chars
    })

    it('truncates long titles', () => {
      const longTitle = 'a'.repeat(300)
      const msg = formatTaskCommitMessage('x', longTitle)
      expect(msg.length).toBeLessThan(260) // 'Task x: ' + 200 chars
    })

    it('is deterministic', () => {
      const opts = { taskId: 'x', title: 'y' }
      expect(formatTaskCommitMessage(opts.taskId, opts.title)).toBe(
        formatTaskCommitMessage(opts.taskId, opts.title)
      )
    })
  })

  describe('formatTaskPRTitle (pure)', () => {
    it('formats PR title with title', () => {
      const title = formatTaskPRTitle('task-123', 'Add login button')
      expect(title).toBe('[Task] Add login button')
    })

    it('formats PR title with taskId only', () => {
      const title = formatTaskPRTitle('task-123')
      expect(title).toBe('[Task task-123]')
    })

    it('formats PR title with empty inputs', () => {
      const title = formatTaskPRTitle('', '')
      expect(title).toBe('[Task unknown]')
    })

    it('truncates long titles', () => {
      const longTitle = 'a'.repeat(300)
      const title = formatTaskPRTitle('x', longTitle)
      expect(title.length).toBeLessThan(220) // '[Task] ' + 200 chars
    })
  })

  describe('formatTaskPRBody (pure)', () => {
    it('formats PR body with all fields', () => {
      const body = formatTaskPRBody({
        taskId: 'task-123',
        title: 'Add login button',
        fileCount: 5,
        slug: 'my-company',
      })
      expect(body).toContain('## Task Summary')
      expect(body).toContain('**Title:** Add login button')
      expect(body).toContain('**Task ID:** task-123')
      expect(body).toContain('**Company:** my-company')
      expect(body).toContain('**Files changed:** 5')
      expect(body).toContain('Generated by Cody')
    })

    it('formats PR body without title', () => {
      const body = formatTaskPRBody({
        taskId: 'task-123',
        fileCount: 3,
        slug: 'my-company',
      })
      expect(body).toContain('**Task ID:** task-123')
      expect(body).not.toContain('**Title:**')
    })
  })

  describe('validateTaskSync (pure)', () => {
    it('validates valid input', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files: { 'App.tsx': 'code' },
      })
      expect(result.valid).toBe(true)
      expect(result.reason).toBeUndefined()
    })

    it('rejects missing taskId', () => {
      const result = validateTaskSync({
        slug: 'my-company',
        files: { 'App.tsx': 'code' },
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toBe('taskId is required')
    })

    it('rejects empty taskId', () => {
      const result = validateTaskSync({
        taskId: '   ',
        slug: 'my-company',
        files: { 'App.tsx': 'code' },
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toBe('taskId is required')
    })

    it('rejects missing slug', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        files: { 'App.tsx': 'code' },
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toBe('slug is required')
    })

    it('rejects missing files', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toBe('files are required')
    })

    it('rejects empty files', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files: {},
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toBe('files map is empty')
    })

    it('rejects files without entry file', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files: { 'styles.css': 'code' },
      })
      expect(result.valid).toBe(false)
      expect(result.reason).toContain('missing entry file')
    })
  })

  describe('edge cases', () => {
    it('taskBranchName handles dots and underscores', () => {
      const name = taskBranchName('task_v1.2')
      expect(name).toBe('task/task_v1.2')
    })

    it('formatTaskCommitMessage trims whitespace', () => {
      const msg = formatTaskCommitMessage('  task-123  ', '  Add button  ')
      expect(msg).toBe('Task task-123: Add button')
    })

    it('validateTaskSync with nested entry file', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files: { 'src/App.tsx': 'code' },
      })
      expect(result.valid).toBe(true)
    })

    it('validateTaskSync with multiple files including entry', () => {
      const result = validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files: {
          'App.tsx': 'app code',
          'components/Button.tsx': 'button',
          'styles.css': 'styles',
        },
      })
      expect(result.valid).toBe(true)
    })
  })

  describe('integration patterns (mocked)', () => {
    it('task start flow: create branch', () => {
      const steps = [
        'resolveApp (get gitOrg)',
        'createTaskBranch (from main)',
      ]
      expect(steps).toHaveLength(2)
    })

    it('task complete flow: commit + optional PR', () => {
      const steps = [
        'validateTaskSync',
        'resolveApp (get gitOrg)',
        'createBranchForTask (ensure branch)',
        'pushFilesToBranch',
        'getBranch (updated SHA)',
        'createTaskPR (if createPR)',
      ]
      expect(steps).toHaveLength(6)
    })
  })
})

describe('performance characteristics', () => {
  it('formatTaskCommitMessage is O(1)', () => {
    const start = performance.now()
    for (let i = 0; i < 10000; i++) {
      formatTaskCommitMessage('task-123', 'Add button')
    }
    const elapsed = performance.now() - start
    expect(elapsed).toBeLessThan(100)
  })

  it('formatTaskPRBody is O(1)', () => {
    const start = performance.now()
    for (let i = 0; i < 10000; i++) {
      formatTaskPRBody({
        taskId: 'task-123',
        title: 'Add button',
        fileCount: 5,
        slug: 'my-company',
      })
    }
    const elapsed = performance.now() - start
    expect(elapsed).toBeLessThan(100)
  })

  it('validateTaskSync is O(n) in file count', () => {
    const files: Record<string, string> = { 'App.tsx': 'entry' }
    for (let i = 0; i < 100; i++) {
      files[`file${i}.tsx`] = 'content'
    }

    const start = performance.now()
    for (let i = 0; i < 100; i++) {
      validateTaskSync({
        taskId: 'task-123',
        slug: 'my-company',
        files,
      })
    }
    const elapsed = performance.now() - start
    expect(elapsed).toBeLessThan(100)
  })
})
