onlyBuiltDependencies:
  - '@ainative/cody-cli'
  - '@anthropic-ai/claude-code'
  - '@sentry/cli'
  - bufferutil
  - es5-ext
  - esbuild
  - protobufjs
  - redis-memory-server
  - sharp
  - unrs-resolver
