import { ImageResponse } from 'next/og'

export const runtime = 'edge'
export const alt = 'AINative Showcase — production-ready React apps generated by AI'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

export default async function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          background:
            'linear-gradient(135deg, #0f172a 0%, #4f46e5 55%, #7c3aed 100%)',
          fontFamily: 'system-ui, sans-serif',
          padding: '72px',
          position: 'relative',
        }}
      >
        <div style={{ position: 'absolute', top: -120, right: -80, width: 420, height: 420, borderRadius: 9999, background: 'rgba(168,85,247,0.25)', display: 'flex' }} />

        <div style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
          <div style={{ display: 'flex', width: 76, height: 76, borderRadius: 18, background: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' }}>
            <svg width="46" height="40" viewBox="0 0 100 85" fill="none">
              <path d="M19.8676 68.0037L32.1669 83.17C32.3171 83.3551 32.4375 83.5627 32.5512 83.7722C33.4124 85.3588 34.8373 85.4186 35.6263 83.8883C35.7713 83.607 35.8184 83.2872 35.8184 82.9708L35.8183 68.0037L19.8676 68.0037Z" fill="white"/>
              <path d="M73.6886 3.57796H82.2931C85.8061 3.57796 88.6539 6.42579 88.6539 9.93878V25.3821C88.6539 27.1918 89.4248 28.9158 90.7734 30.1225L96.2074 34.9845L90.7734 39.8465C89.4248 41.0532 88.6539 42.7772 88.6539 44.5869V59.2351C88.6539 62.7481 85.8061 65.596 82.2931 65.596H73.6886" stroke="white" strokeWidth="7.1413" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M59.7906 65.596L17.4922 65.596C13.9793 65.596 11.1314 62.7481 11.1314 59.2351L11.1314 43.7918C11.1314 41.9821 10.3606 40.2581 9.01197 39.0514L3.57796 34.1894L9.01197 29.3274C10.3606 28.1207 11.1314 26.3967 11.1314 24.587L11.1314 9.93879C11.1314 6.4258 13.9793 3.57796 17.4923 3.57796L59.7906 3.57797" stroke="white" strokeWidth="7.1413" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <div style={{ fontSize: 34, fontWeight: 700, color: 'rgba(255,255,255,0.95)', letterSpacing: -0.5 }}>AINative Builder</div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ fontSize: 80, fontWeight: 800, color: 'white', lineHeight: 1.03, letterSpacing: -2, marginBottom: 18 }}>
            AI App Showcase
          </div>
          <div style={{ fontSize: 32, color: 'rgba(255,255,255,0.9)', lineHeight: 1.3, maxWidth: 940 }}>
            50+ production-ready React apps — dashboards, CRMs, storefronts,
            agent tools — each built from a single prompt in seconds.
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', gap: 14 }}>
            {['Fully Interactive', 'ZeroDB-backed', 'Copy the prompt'].map((f) => (
              <div key={f} style={{ display: 'flex', padding: '12px 22px', borderRadius: 9999, background: 'rgba(255,255,255,0.16)', color: 'white', fontSize: 20, fontWeight: 600 }}>
                {f}
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', color: 'rgba(255,255,255,0.85)', fontSize: 22, fontWeight: 600 }}>builder.ainative.studio/showcase</div>
        </div>
      </div>
    ),
    { ...size },
  )
}
