/**
 * Project Exporter — generates a downloadable ZIP of a real working project.
 */

import JSZip from 'jszip'

const DEFAULT_PACKAGE_JSON = {
  name: 'ainative-app',
  version: '1.0.0',
  private: true,
  scripts: {
    dev: 'next dev',
    build: 'next build',
    start: 'next start',
  },
  dependencies: {
    next: '^14.0.0',
    react: '^18.2.0',
    'react-dom': '^18.2.0',
    'lucide-react': '^0.344.0',
    recharts: '^2.15.0',
    clsx: '^2.1.0',
    'tailwind-merge': '^2.2.0',
  },
  devDependencies: {
    typescript: '^5.3.0',
    '@types/react': '^18.2.0',
    '@types/react-dom': '^18.2.0',
    tailwindcss: '^3.4.0',
    postcss: '^8.4.0',
    autoprefixer: '^10.4.0',
  },
}

const DEFAULT_NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig
`

const DEFAULT_TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './app/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
}
`

const DEFAULT_POSTCSS_CONFIG = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`

const DEFAULT_TSCONFIG = `{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] },
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`

/**
 * Export files as a downloadable ZIP project.
 */
export async function exportProject(
  files: Record<string, string>,
  appName: string
): Promise<Uint8Array> {
  const zip = new JSZip()
  const projectName = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-')

  // Add all generated files
  for (const [path, content] of Object.entries(files)) {
    const cleanPath = path.startsWith('/') ? path.slice(1) : path
    zip.file(cleanPath, content)
  }

  // Ensure essential config files exist
  if (!files['/package.json'] && !files['package.json']) {
    const pkg = { ...DEFAULT_PACKAGE_JSON, name: projectName }
    zip.file('package.json', JSON.stringify(pkg, null, 2))
  }

  if (!files['/tsconfig.json'] && !files['tsconfig.json']) {
    zip.file('tsconfig.json', DEFAULT_TSCONFIG)
  }

  if (!files['/next.config.js'] && !files['next.config.js']) {
    zip.file('next.config.js', DEFAULT_NEXT_CONFIG)
  }

  if (!files['/tailwind.config.js'] && !files['tailwind.config.js'] && !files['/tailwind.config.ts'] && !files['tailwind.config.ts']) {
    zip.file('tailwind.config.js', DEFAULT_TAILWIND_CONFIG)
  }

  if (!files['/postcss.config.js'] && !files['postcss.config.js']) {
    zip.file('postcss.config.js', DEFAULT_POSTCSS_CONFIG)
  }

  // Add README
  if (!files['/README.md'] && !files['README.md']) {
    zip.file('README.md', `# ${appName}

Generated by [AINative Builder Studio](https://ainative.studio)

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.
`)
  }

  // Add .gitignore
  if (!files['/.gitignore'] && !files['.gitignore']) {
    zip.file('.gitignore', 'node_modules/\n.next/\n.env\n.env.local\n')
  }

  return zip.generateAsync({ type: 'uint8array' })
}
