import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import Link from 'next/link'
import { PublicNav } from '@/components/shared/public-nav'
import { PublicFooter } from '@/components/shared/public-footer'
import { GUIDES, GUIDE_SLUGS, getGuideBySlug } from '@/lib/data/seo-guides'
import { sectionAnchors } from '@/lib/help/stuck-search'
import { ImStuck } from '@/components/help/ImStuck'

interface PageProps {
  params: Promise<{ slug: string }>
}

const BASE_URL = 'https://builder.ainative.studio'

// Statically pre-render one page per guide so every article is crawlable and
// indexable without hitting the database at request time.
export function generateStaticParams() {
  return GUIDE_SLUGS.map((slug) => ({ slug }))
}

export const dynamicParams = false

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params
  const guide = getGuideBySlug(slug)

  if (!guide) {
    return { title: 'Guide Not Found | AINative Builder' }
  }

  const title = `${guide.title} | AINative Builder`

  return {
    title,
    description: guide.excerpt,
    keywords: [...guide.keywords, ...guide.tags, 'AINative Builder'],
    authors: [{ name: 'AINative' }],
    openGraph: {
      title,
      description: guide.excerpt,
      type: 'article',
      url: `${BASE_URL}/guides/${slug}`,
      publishedTime: guide.datePublished,
      modifiedTime: guide.dateModified,
      tags: guide.tags,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description: guide.excerpt,
    },
    alternates: {
      canonical: `${BASE_URL}/guides/${slug}`,
    },
  }
}

export default async function GuidePage({ params }: PageProps) {
  const { slug } = await params
  const guide = getGuideBySlug(slug)

  if (!guide) {
    notFound()
  }

  // Related guides: same tags first, then any others.
  const related = GUIDES.filter(
    (g) => g.slug !== guide.slug && g.tags.some((t) => guide.tags.includes(t))
  )
  const relatedGuides = (
    related.length > 0 ? related : GUIDES.filter((g) => g.slug !== guide.slug)
  ).slice(0, 3)

  // Stable, slugified anchors for every section + FAQ — generated by the SAME
  // helper the "I'm stuck" search catalog uses (lib/help/stuck-search.ts), so
  // its deep links (/guides/{slug}#{anchor}) always land on a real element.
  const anchors = sectionAnchors(guide.sections.map((s) => s.heading))
  const faqAnchors = sectionAnchors(guide.faqs.map((f) => f.question), 'faq')

  const articleJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: guide.title,
    description: guide.excerpt,
    articleSection: guide.category,
    keywords: guide.keywords.join(', '),
    datePublished: guide.datePublished,
    dateModified: guide.dateModified,
    author: { '@type': 'Organization', name: 'AINative' },
    publisher: {
      '@type': 'Organization',
      name: 'AINative Builder',
      url: BASE_URL,
    },
    mainEntityOfPage: {
      '@type': 'WebPage',
      '@id': `${BASE_URL}/guides/${slug}`,
    },
  }

  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: guide.faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: { '@type': 'Answer', text: faq.answer },
    })),
  }

  const breadcrumbJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Guides', item: `${BASE_URL}/guides` },
      {
        '@type': 'ListItem',
        position: 2,
        name: guide.title,
        item: `${BASE_URL}/guides/${slug}`,
      },
    ],
  }

  return (
    <div className="modernist" style={{ minHeight: '100vh' }}>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <PublicNav />

      <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px' }}>
        {/* Breadcrumb */}
        <nav className="m-mono" style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 32 }} aria-label="Breadcrumb">
          <Link href="/guides" style={{ color: 'inherit' }}>Guides</Link>
          <span style={{ margin: '0 8px' }}>/</span>
          <span style={{ color: 'var(--color-text)' }}>{guide.title}</span>
        </nav>

        {/* Header */}
        <article>
          <header style={{ marginBottom: 32 }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 12, marginBottom: 16 }}>
              <span className="m-mono" style={{ fontSize: 10.5, textTransform: 'uppercase', letterSpacing: '.08em', color: 'var(--color-accent)' }}>{guide.category}</span>
              <span className="m-mono" style={{ fontSize: 12, color: 'var(--text-muted)' }}>
                {guide.readTimeMinutes} min read
              </span>
              <span style={{ color: 'var(--text-faint)' }}>·</span>
              <time className="m-mono" style={{ fontSize: 12, color: 'var(--text-muted)' }} dateTime={guide.dateModified}>
                Updated{' '}
                {new Date(guide.dateModified).toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric',
                })}
              </time>
            </div>
            <h1 className="m-h1" style={{ margin: '0 0 16px' }}>{guide.title}</h1>
            <p style={{ fontSize: 17, color: 'var(--text-muted)', lineHeight: 1.6 }}>
              {guide.intro}
            </p>
          </header>

          {/* Body sections */}
          <div style={{ display: 'grid', gap: 40 }}>
            {guide.sections.map((section, i) => (
              <section key={section.heading} id={anchors[i]} style={{ scrollMarginTop: 96 }}>
                <h2 style={{ fontFamily: 'var(--font-heading)', fontWeight: 700, fontSize: 24, marginBottom: 16 }}>{section.heading}</h2>
                <div style={{ display: 'grid', gap: 16 }}>
                  {section.paragraphs.map((para, i) => (
                    <p key={i} style={{ color: 'var(--text-muted)', lineHeight: 1.7 }}>
                      {para}
                    </p>
                  ))}
                </div>
                {section.bullets && section.bullets.length > 0 && (
                  <ul style={{ marginTop: 16, display: 'grid', gap: 8, listStyle: 'none', padding: 0 }}>
                    {section.bullets.map((bullet) => (
                      <li key={bullet} style={{ display: 'flex', gap: 12 }}>
                        <span aria-hidden style={{ color: 'var(--color-accent)', flexShrink: 0 }}>✓</span>
                        <span style={{ color: 'var(--text-muted)' }}>{bullet}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>

          {/* CTA */}
          <div style={{ borderTop: '2px solid var(--color-divider)', marginTop: 48, paddingTop: 40, textAlign: 'center' }}>
            <h2 className="m-h1" style={{ fontSize: 26, margin: '0 auto 12px' }}>Start building with AI</h2>
            <p style={{ color: 'var(--text-muted)', marginBottom: 24 }}>
              Turn a prompt into a production-ready app in seconds with AINative
              Builder.
            </p>
            <Link href="/" className="btn-primary" style={{ textDecoration: 'none' }}>Try AINative Builder Free</Link>
          </div>

          {/* FAQ */}
          {guide.faqs.length > 0 && (
            <section style={{ borderTop: '2px solid var(--color-divider)', marginTop: 48, paddingTop: 40 }}>
              <h2 className="m-h1" style={{ fontSize: 26, margin: '0 0 24px' }}>Frequently asked questions</h2>
              <div style={{ display: 'grid', gap: 24 }}>
                {guide.faqs.map((faq, i) => (
                  <div key={faq.question} id={faqAnchors[i]} style={{ border: '1.5px solid var(--color-divider)', padding: 24, scrollMarginTop: 96 }}>
                    <h3 style={{ fontFamily: 'var(--font-heading)', fontWeight: 700, fontSize: 18, marginBottom: 12 }}>{faq.question}</h3>
                    <p style={{ color: 'var(--text-muted)', lineHeight: 1.6 }}>
                      {faq.answer}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          )}
        </article>

        {/* Related guides — internal linking for SEO */}
        {relatedGuides.length > 0 && (
          <section style={{ borderTop: '2px solid var(--color-divider)', marginTop: 48, paddingTop: 40 }}>
            <h2 style={{ fontFamily: 'var(--font-heading)', fontWeight: 700, fontSize: 20, marginBottom: 24 }}>Related guides</h2>
            <div style={{ display: 'grid', gap: 2, gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', background: 'var(--color-divider)' }}>
              {relatedGuides.map((rel) => (
                <Link
                  key={rel.slug}
                  href={`/guides/${rel.slug}`}
                  style={{ background: 'var(--color-bg)', padding: 16, textDecoration: 'none', color: 'inherit' }}
                >
                  <span className="m-mono" style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '.08em', color: 'var(--color-accent)', display: 'block', marginBottom: 8 }}>
                    {rel.category}
                  </span>
                  <h3 style={{ fontFamily: 'var(--font-heading)', fontWeight: 700, marginBottom: 4 }}>{rel.title}</h3>
                  <p style={{ fontSize: 13, color: 'var(--text-muted)', overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' }}>
                    {rel.excerpt}
                  </p>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* "I'm stuck" jump-to-answer (#321) — searches the FULL guides/FAQ
            catalog, not just this article, and deep-links into the answer. */}
        <section style={{ borderTop: '2px solid var(--color-divider)', marginTop: 48, paddingTop: 40 }} aria-label="Stuck? Find the answer">
          <ImStuck />
        </section>
      </main>
      <PublicFooter />
    </div>
  )
}
