// Generated by LLAMA API - Modern SaaS Landing Page
import React from 'react';

// Hero Section Component
export const HeroSection = () => {
  return (
    <section className="bg-gradient-to-r from-blue-500 to-purple-600 text-white py-20">
      <div className="container mx-auto px-4 text-center">
        <h1 className="text-5xl font-bold mb-4">Unlock Your Potential</h1>
        <p className="text-lg mb-8">Discover the power of our SaaS product</p>
        <button className="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded">
          Get Started
        </button>
      </div>
    </section>
  );
};

// Features Grid Component
export const FeaturesGrid = () => {
  const features = [
    { title: 'Feature 1', description: 'This is feature 1' },
    { title: 'Feature 2', description: 'This is feature 2' },
    { title: 'Feature 3', description: 'This is feature 3' },
    { title: 'Feature 4', description: 'This is feature 4' },
  ];

  return (
    <section className="py-20">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-8 text-center">Features</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-white shadow-md p-6 rounded">
              <h3 className="text-lg font-bold mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// Pricing Cards Component
export const PricingCards = () => {
  const plans = [
    {
      title: 'Basic',
      price: '$9.99/month',
      features: ['Feature 1', 'Feature 2'],
    },
    {
      title: 'Premium',
      price: '$19.99/month',
      features: ['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'],
    },
    {
      title: 'Enterprise',
      price: 'Custom',
      features: ['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4', 'Feature 5'],
    },
  ];

  return (
    <section className="py-20 bg-gray-100">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold mb-8 text-center">Pricing</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {plans.map((plan, index) => (
            <div key={index} className="bg-white shadow-md p-6 rounded">
              <h3 className="text-lg font-bold mb-2">{plan.title}</h3>
              <p className="text-gray-600 mb-4">{plan.price}</p>
              <ul className="list-disc list-inside mb-4">
                {plan.features.map((feature, featureIndex) => (
                  <li key={featureIndex}>{feature}</li>
                ))}
              </ul>
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Get Started
              </button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

// Complete Landing Page
const LandingPage = () => {
  return (
    <div>
      <HeroSection />
      <FeaturesGrid />
      <PricingCards />
    </div>
  );
};

export default LandingPage;