/**
 * AINative File Generator
 * Generates the complete AINative file set for every generated application:
 * - robots.txt (crawler rules for search + AI agents)
 * - sitemap.xml (SEO sitemap)
 * - llms.txt (AI agent discovery — AINative standard)
 * - .well-known/ai-plugin.json (ChatGPT/agent plugin manifest)
 * - .well-known/security.txt (trust signal)
 * - Enhanced JSON-LD structured data
 * - Next.js metadata (layout.tsx with SEO)
 * - Next.js robots.ts and sitemap.ts
 */

export interface AppMetadata {
  name: string
  description: string
  type: 'saas' | 'dashboard' | 'ecommerce' | 'marketplace' | 'chat' | 'docs' | 'admin' | 'portfolio' | 'blog' | 'agent'
  features: string[]
  pages: string[]
  domain?: string
}

/**
 * Extract app metadata from the user prompt and generated code
 */
export function extractAppMetadata(prompt: string, code: string): AppMetadata {
  const lower = prompt.toLowerCase()

  // Extract app name from code (function name) or prompt
  const nameMatch = code.match(/function\s+([A-Z][a-zA-Z]+)/)
  const promptNameMatch = prompt.match(/called\s+(\w+)/i) || prompt.match(/for\s+(\w+)/i)
  const name = promptNameMatch?.[1] || nameMatch?.[1] || 'AINativeApp'

  // Detect type
  let type: AppMetadata['type'] = 'saas'
  if (lower.includes('dashboard') || lower.includes('analytics') || lower.includes('monitor')) type = 'dashboard'
  else if (lower.includes('ecommerce') || lower.includes('store') || lower.includes('shop') || lower.includes('product')) type = 'ecommerce'
  else if (lower.includes('marketplace') || lower.includes('hub')) type = 'marketplace'
  else if (lower.includes('chat') || lower.includes('assistant') || lower.includes('conversation')) type = 'chat'
  else if (lower.includes('docs') || lower.includes('documentation') || lower.includes('api')) type = 'docs'
  else if (lower.includes('admin') || lower.includes('panel') || lower.includes('management')) type = 'admin'
  else if (lower.includes('agent') || lower.includes('swarm') || lower.includes('monitor')) type = 'agent'
  else if (lower.includes('blog') || lower.includes('article')) type = 'blog'
  else if (lower.includes('portfolio')) type = 'portfolio'

  // Extract features
  const features: string[] = []
  if (lower.includes('pricing')) features.push('Pricing plans')
  if (lower.includes('testimonial')) features.push('Customer testimonials')
  if (lower.includes('feature')) features.push('Feature showcase')
  if (lower.includes('hero')) features.push('Hero section')
  if (lower.includes('chart') || lower.includes('analytics')) features.push('Data visualization')
  if (lower.includes('table') || lower.includes('data')) features.push('Data management')
  if (lower.includes('auth') || lower.includes('login')) features.push('Authentication')
  if (lower.includes('search')) features.push('Search functionality')
  if (lower.includes('filter')) features.push('Filtering')
  if (lower.includes('agent')) features.push('AI agent management')
  if (lower.includes('safety') || lower.includes('guardrail')) features.push('AI safety controls')

  // Extract pages
  const pages = ['/', '/features', '/pricing', '/about']
  if (type === 'dashboard') pages.push('/dashboard', '/analytics', '/settings')
  if (type === 'ecommerce') pages.push('/products', '/cart', '/checkout')
  if (type === 'docs') pages.push('/docs', '/api-reference', '/quickstart')
  if (type === 'agent') pages.push('/agents', '/swarms', '/safety', '/traces')

  return { name, description: prompt.slice(0, 200), type, features, pages }
}

/**
 * Generate robots.txt with AI agent crawler rules
 */
export function generateRobotsTxt(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`
  return `# AINative Robots.txt — Optimized for search engines AND AI agents
# Generated by AINative Builder Studio

User-agent: *
Allow: /
Disallow: /api/
Disallow: /admin/
Disallow: /_next/

# AI Agent Crawler Rules (AINative Standard)
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: CCBot
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Bytespider
Disallow: /

Sitemap: ${domain}/sitemap.xml
`
}

/**
 * Generate sitemap.xml
 */
export function generateSitemapXml(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`
  const now = new Date().toISOString().split('T')[0]

  const urls = meta.pages.map((page, i) => {
    const priority = i === 0 ? '1.0' : i <= 2 ? '0.8' : '0.6'
    return `  <url>
    <loc>${domain}${page}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>${i === 0 ? 'weekly' : 'monthly'}</changefreq>
    <priority>${priority}</priority>
  </url>`
  }).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>`
}

/**
 * Generate llms.txt — AINative standard for AI agent discovery
 */
export function generateLlmsTxt(meta: AppMetadata): string {
  const featureList = meta.features.map(f => `- ${f}`).join('\n')
  const pageList = meta.pages.map(p => `- ${p}`).join('\n')

  return `# ${meta.name}
# llms.txt — Machine-readable application summary for AI agents
# AINative Standard v1.0

## What is ${meta.name}?
${meta.description}

## Application Type
${meta.type}

## Key Features
${featureList || '- Full-featured web application'}

## Pages
${pageList}

## Technology
- Framework: Next.js 14 (App Router)
- UI: AINative Design System + shadcn/ui
- Icons: Lucide React
- Charts: Recharts
- AX Standard: AINative AX 10/10

## Contact
- Website: https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app
- Support: support@${meta.name.toLowerCase().replace(/\s+/g, '')}.app

## API
- Base URL: /api/v1
- Auth: Bearer token
- Docs: /docs/api-reference
`
}

/**
 * Generate .well-known/ai-plugin.json for ChatGPT/agent plugin discovery
 */
export function generateAiPluginJson(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`

  return JSON.stringify({
    schema_version: 'v1',
    name_for_human: meta.name,
    name_for_model: meta.name.toLowerCase().replace(/\s+/g, '_'),
    description_for_human: meta.description,
    description_for_model: `${meta.name} is a ${meta.type} application. ${meta.features.join('. ')}.`,
    auth: {
      type: 'none',
    },
    api: {
      type: 'openapi',
      url: `${domain}/.well-known/openapi.json`,
    },
    logo_url: `${domain}/icon.png`,
    contact_email: `support@${meta.name.toLowerCase().replace(/\s+/g, '')}.app`,
    legal_info_url: `${domain}/legal`,
  }, null, 2)
}

/**
 * Generate .well-known/security.txt
 */
export function generateSecurityTxt(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`
  const expires = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()

  return `Contact: security@${meta.name.toLowerCase().replace(/\s+/g, '')}.app
Expires: ${expires}
Preferred-Languages: en
Canonical: ${domain}/.well-known/security.txt
Policy: ${domain}/security-policy
`
}

/**
 * Generate Next.js robots.ts file content
 */
export function generateNextRobotsTs(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`

  return `import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: '*', allow: '/', disallow: ['/api/', '/admin/', '/_next/'] },
      {
        userAgent: ['GPTBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-Web', 'anthropic-ai', 'CCBot', 'Google-Extended', 'PerplexityBot'],
        allow: '/',
      },
    ],
    sitemap: '${domain}/sitemap.xml',
  }
}
`
}

/**
 * Generate Next.js sitemap.ts file content
 */
export function generateNextSitemapTs(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`

  const entries = meta.pages.map((page, i) => {
    const priority = i === 0 ? 1 : i <= 2 ? 0.8 : 0.6
    const freq = i === 0 ? 'weekly' : 'monthly'
    return `    { url: '${domain}${page}', lastModified: now, changeFrequency: '${freq}' as const, priority: ${priority} },`
  }).join('\n')

  return `import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date().toISOString()
  return [
${entries}
  ]
}
`
}

/**
 * Generate Next.js layout.tsx with full SEO metadata
 */
export function generateNextLayoutTs(meta: AppMetadata): string {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`

  return `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${meta.name} — ${meta.type.charAt(0).toUpperCase() + meta.type.slice(1)} Application',
  description: '${meta.description.replace(/'/g, "\\'")}',
  metadataBase: new URL('${domain}'),
  openGraph: {
    title: '${meta.name}',
    description: '${meta.description.replace(/'/g, "\\'").slice(0, 160)}',
    url: '${domain}',
    siteName: '${meta.name}',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: '${meta.name}',
    description: '${meta.description.replace(/'/g, "\\'").slice(0, 160)}',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`
}

/**
 * Generate enhanced JSON-LD structured data
 */
export function generateJsonLd(meta: AppMetadata): object {
  const domain = meta.domain || `https://${meta.name.toLowerCase().replace(/\s+/g, '')}.app`

  const base: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': meta.type === 'ecommerce' ? 'Store' : meta.type === 'blog' ? 'Blog' : 'WebApplication',
    name: meta.name,
    description: meta.description,
    url: domain,
    applicationCategory: meta.type === 'ecommerce' ? 'ShoppingApplication' : meta.type === 'dashboard' ? 'BusinessApplication' : 'SoftwareApplication',
    operatingSystem: 'Web',
    featureList: meta.features,
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
    },
  }

  return base
}

/**
 * Generate the complete AINative file set. `overrides` lets a caller with real,
 * durable company data (name/tagline/live URL — from app-registry.ts, not the
 * heuristic keyword-matching extractAppMetadata does on the raw idea prompt)
 * replace the guessed fields — used by the live-serving route (#493) so a
 * founder's real domain/name appears instead of a placeholder `{name}.app`.
 */
export function generateAINativeFileSet(
  prompt: string,
  code: string,
  overrides: Partial<Pick<AppMetadata, 'name' | 'description' | 'domain'>> = {},
): Record<string, string> {
  const meta = { ...extractAppMetadata(prompt, code), ...overrides }

  return {
    'public/robots.txt': generateRobotsTxt(meta),
    'public/sitemap.xml': generateSitemapXml(meta),
    'public/llms.txt': generateLlmsTxt(meta),
    'public/.well-known/ai-plugin.json': generateAiPluginJson(meta),
    'public/.well-known/security.txt': generateSecurityTxt(meta),
    'app/robots.ts': generateNextRobotsTs(meta),
    'app/sitemap.ts': generateNextSitemapTs(meta),
    'app/layout.tsx': generateNextLayoutTs(meta),
  }
}
