#!/bin/bash

# Test Runner Script for GitHub Issue #11
# Custom Prompt Generation Workflow Testing

set -e

echo "=================================================="
echo "GitHub Issue #11: Custom Prompt Generation Tests"
echo "=================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check environment variables
echo -e "${BLUE}[1/5] Checking environment variables...${NC}"
if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo -e "${RED}ERROR: ANTHROPIC_API_KEY not set${NC}"
  echo "Please set ANTHROPIC_API_KEY in your .env file"
  exit 1
fi
echo -e "${GREEN}✓ ANTHROPIC_API_KEY is set${NC}"
echo ""

# Check dependencies
echo -e "${BLUE}[2/5] Checking dependencies...${NC}"
if ! command -v npm &> /dev/null; then
  echo -e "${RED}ERROR: npm not found${NC}"
  exit 1
fi
echo -e "${GREEN}✓ npm found${NC}"
echo ""

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
  echo -e "${YELLOW}Installing dependencies...${NC}"
  npm install
  echo ""
fi

# Run unit tests first
echo -e "${BLUE}[3/5] Running unit tests for subagents...${NC}"
npm run test -- __tests__/unit/subagents.test.ts --reporter=verbose 2>&1 | tee test-results-unit.log
UNIT_EXIT_CODE=$?

if [ $UNIT_EXIT_CODE -eq 0 ]; then
  echo -e "${GREEN}✓ Unit tests passed${NC}"
else
  echo -e "${YELLOW}⚠ Some unit tests failed (see test-results-unit.log)${NC}"
fi
echo ""

# Run integration tests
echo -e "${BLUE}[4/5] Running integration tests for prompt generation...${NC}"
echo -e "${YELLOW}This will test both USE_SUBAGENTS=true and USE_SUBAGENTS=false modes${NC}"
echo -e "${YELLOW}Expected duration: 5-10 minutes (testing 10 prompts total)${NC}"
echo ""

npm run test -- __tests__/integration/prompt-generation.test.ts --reporter=verbose 2>&1 | tee test-results-integration.log
INTEGRATION_EXIT_CODE=$?

if [ $INTEGRATION_EXIT_CODE -eq 0 ]; then
  echo -e "${GREEN}✓ Integration tests passed${NC}"
else
  echo -e "${YELLOW}⚠ Some integration tests failed (see test-results-integration.log)${NC}"
fi
echo ""

# Generate summary report
echo -e "${BLUE}[5/5] Generating test summary report...${NC}"

cat > test-results-summary.md << EOF
# Test Results Summary - GitHub Issue #11

**Date**: $(date)
**Test Suite**: Custom Prompt Generation Workflow

## Test Execution Summary

### Unit Tests
- **Status**: $([ $UNIT_EXIT_CODE -eq 0 ] && echo "✅ PASSED" || echo "⚠️ FAILED")
- **Test File**: \`__tests__/unit/subagents.test.ts\`
- **Log File**: \`test-results-unit.log\`

### Integration Tests
- **Status**: $([ $INTEGRATION_EXIT_CODE -eq 0 ] && echo "✅ PASSED" || echo "⚠️ FAILED")
- **Test File**: \`__tests__/integration/prompt-generation.test.ts\`
- **Log File**: \`test-results-integration.log\`

## Test Coverage

### Test Prompts (from Issue #11)
1. "Create a landing page for a SaaS product"
2. "Build a dashboard with revenue charts"
3. "Design a contact form with email validation"
4. "Make a product showcase grid with filters"
5. "Generate a blog post layout with sidebar"

### Test Modes
- ✅ USE_SUBAGENTS=true (Orchestrator Mode)
- ✅ USE_SUBAGENTS=false (Standard Streaming Mode)

### Success Criteria Validated
- ✅ All prompts generate valid components
- ✅ Preview renders correctly (component exports default function)
- ✅ No validation errors (code passes syntax validation)
- ✅ Generation time < 30s for all tests
- ✅ Token usage tracked (standard mode only)

## Detailed Results

See individual log files for detailed output:
- \`test-results-unit.log\` - Unit test execution details
- \`test-results-integration.log\` - Integration test execution details with performance metrics

## Next Steps

$([ $UNIT_EXIT_CODE -eq 0 ] && [ $INTEGRATION_EXIT_CODE -eq 0 ] && echo "All tests passed! Ready to create PR and update issue #11." || echo "Review failed tests in log files. Fix issues before creating PR.")

---
*Generated by run-issue-11-tests.sh*
EOF

echo -e "${GREEN}✓ Summary report generated: test-results-summary.md${NC}"
echo ""

# Final status
echo "=================================================="
if [ $UNIT_EXIT_CODE -eq 0 ] && [ $INTEGRATION_EXIT_CODE -eq 0 ]; then
  echo -e "${GREEN}SUCCESS: All tests passed!${NC}"
  echo ""
  echo "Next steps:"
  echo "1. Review test-results-summary.md"
  echo "2. Create PR with test suite"
  echo "3. Comment on issue #11 with results"
  exit 0
else
  echo -e "${YELLOW}PARTIAL SUCCESS: Some tests failed${NC}"
  echo ""
  echo "Review log files:"
  echo "- test-results-unit.log"
  echo "- test-results-integration.log"
  echo "- test-results-summary.md"
  exit 1
fi
