/**
 * Design System Picker — the MVP catalog of 6 systems (#590).
 *
 * Data below is transcribed exactly from the real theme.json files in the
 * source drop (`~/Downloads/Design systems for builder product/systems/`),
 * except Modernist, whose values come from the LIVE codebase (app/modernist.css)
 * — Modernist is Builder's own existing chrome, already confirmed identical to
 * its counterpart export in that same drop's `_ds/modernist-<uuid>/` bundle.
 *
 * Do not hand-edit values here without re-checking the source file — this
 * catalog is the single source of truth for both the picker UI (#591) and
 * the codegen prompt injection (#592).
 */

import type { DesignSystem } from './types'

export const DESIGN_SYSTEMS: DesignSystem[] = [
  {
    id: 'modernist',
    name: 'Modernist',
    series: 'builder',
    primitive: null,
    direction: "Builder's own current look — brutalist editorial, machine-speech UI",
    palette: {
      band: 'light',
      bg: '#f3f2f2',
      surface: '#e9e7e7',
      text: '#201e1d',
      accent: '#ec3013',
      accent2: '#d7d3d3',
      // Modernist has no per-status semantic palette in the live codebase —
      // omitted rather than fabricated (see types.ts's doc comment).
    },
    fonts: {
      heading: { family: 'Archivo', weights: [400, 500, 600, 700, 800] },
      body: { family: 'Archivo', weights: [400, 500, 600, 700] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: null,
  },
  {
    id: 'noir',
    name: 'Noir',
    series: 'foundation',
    primitive: null,
    direction: 'Luxury fashion',
    palette: {
      band: 'dark',
      bg: '#101010',
      surface: '#181818',
      text: '#f2efe9',
      accent: '#c9b27c',
      accent2: '#f2efe9',
      status: { running: '#c9b27c', success: '#81bb8d', warning: '#dbb879', error: '#de958e', info: '#7fafe2' },
    },
    fonts: {
      heading: { family: 'Cormorant', weights: [300, 400, 500] },
      body: { family: 'Jost', weights: [300, 400, 500] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/noir/styles.css',
  },
  {
    id: 'crayon',
    name: 'Crayon',
    series: 'foundation',
    primitive: null,
    direction: 'Playful / toy',
    palette: {
      band: 'light',
      bg: '#fff8ec',
      surface: '#ffffff',
      text: '#2a1f3d',
      accent: '#ff5c8a',
      accent2: '#ffb703',
      status: { running: '#ff5c8a', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Fredoka', weights: [600, 700] },
      body: { family: 'Nunito', weights: [400, 600, 700] },
    },
    radius: 16,
    shadows: 'hard',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/crayon/styles.css',
  },
  {
    id: 'cody',
    name: 'Cody',
    series: 'ainative',
    primitive: 'Cody (CTO agent)',
    direction: 'Pair-programming agent',
    palette: {
      band: 'dark',
      bg: '#0b1220',
      surface: '#111827',
      text: '#e5e7eb',
      accent: '#7dd3fc',
      accent2: '#f59e0b',
      status: { running: '#7dd3fc', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Geist Mono', weights: [500, 700] },
      body: { family: 'Geist', weights: [400, 500, 600] },
    },
    radius: 4,
    shadows: 'none',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/cody/styles.css',
  },
  {
    id: 'outrun',
    name: 'Outrun',
    series: 'foundation',
    primitive: null,
    direction: 'Neo-retro 80s',
    palette: {
      band: 'dark',
      bg: '#140a2b',
      surface: '#1e1040',
      text: '#fbeaff',
      accent: '#ff2fa0',
      accent2: '#2ee6ff',
      status: { running: '#ff2fa0', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Orbitron', weights: [500, 700, 900] },
      body: { family: 'Exo 2', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'glow',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/outrun/styles.css',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    series: 'ainative',
    primitive: 'AI COGS',
    direction: 'Economics & cost accounting',
    palette: {
      band: 'light',
      bg: '#fbfaf6',
      surface: '#f3f1ea',
      text: '#1e2a1f',
      accent: '#1f6f43',
      accent2: '#b8860b',
      status: { running: '#1f6f43', success: '#3f774d', warning: '#9b7b3c', error: '#96534e', info: '#3e6c9b' },
    },
    fonts: {
      heading: { family: 'Libre Franklin', weights: [500, 600, 700] },
      body: { family: 'JetBrains Mono', weights: [400, 500] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'halftone',
    brandBound: false,
    stylesheetPath: '/design-systems/ledger/styles.css',
  },
  {
    id: 'approval',
    name: 'Approval',
    series: 'ainative',
    primitive: 'AIKit · human-in-the-loop',
    direction: 'Human-in-the-loop',
    palette: {
      band: 'light',
      bg: '#ffffff',
      surface: '#f5f7fb',
      text: '#14213d',
      accent: '#e63946',
      accent2: '#2a9d8f',
      status: { running: '#e63946', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Manrope', weights: [600, 700, 800] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 4,
    shadows: 'soft',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/approval/styles.css',
  },
  {
    id: 'chrome',
    name: 'Chrome',
    series: 'foundation',
    primitive: null,
    direction: 'Y2K',
    palette: {
      band: 'light',
      bg: '#e9edf5',
      surface: '#f7f9fd',
      text: '#0b1a3a',
      accent: '#0057ff',
      accent2: '#ff5ad1',
      status: { running: '#0057ff', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Unbounded', weights: [500, 700] },
      body: { family: 'Kumbh Sans', weights: [400, 500, 700] },
    },
    radius: 999,
    shadows: 'soft',
    imageTreatment: 'cool',
    brandBound: false,
    stylesheetPath: '/design-systems/chrome/styles.css',
  },
  {
    id: 'cloud',
    name: 'Cloud',
    series: 'ainative',
    primitive: 'Agent Cloud',
    direction: 'Agent runtime & orchestration',
    palette: {
      band: 'dark',
      bg: '#111827',
      surface: '#1f2937',
      text: '#f9fafb',
      accent: '#38bdf8',
      accent2: '#10b981',
      status: { running: '#38bdf8', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'IBM Plex Sans', weights: [500, 600] },
      body: { family: 'IBM Plex Sans', weights: [400, 500, 600] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/cloud/styles.css',
  },
  {
    id: 'concrete',
    name: 'Concrete',
    series: 'foundation',
    primitive: null,
    direction: 'Brutalist',
    palette: {
      band: 'light',
      bg: '#e9e7e2',
      surface: '#dfdcd5',
      text: '#121212',
      accent: '#1f1fff',
      accent2: '#121212',
      status: { running: '#1f1fff', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Space Grotesk', weights: [500, 700] },
      body: { family: 'IBM Plex Mono', weights: [400, 600] },
    },
    radius: 0,
    shadows: 'hard',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/concrete/styles.css',
  },
  {
    id: 'console',
    name: 'Console',
    series: 'foundation',
    primitive: null,
    direction: 'Terminal / hacker',
    palette: {
      band: 'dark',
      bg: '#0a0d0a',
      surface: '#111711',
      text: '#c9f2c2',
      accent: '#3dff6e',
      accent2: '#ffd23d',
      status: { running: '#3dff6e', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'JetBrains Mono', weights: [500, 700] },
      body: { family: 'JetBrains Mono', weights: [400, 500, 700] },
    },
    radius: 0,
    shadows: 'glow',
    imageTreatment: 'phosphor',
    brandBound: false,
    stylesheetPath: '/design-systems/console/styles.css',
  },
  {
    id: 'context',
    name: 'Context',
    series: 'ainative',
    primitive: 'Memory + context layer',
    direction: 'The desk and the cabinet',
    palette: {
      band: 'light',
      bg: '#f7f1e8',
      surface: '#fffaf2',
      text: '#2c2418',
      accent: '#c2410c',
      accent2: '#4a7c59',
      status: { running: '#c2410c', success: '#0a7e3a', warning: '#a4780f', error: '#ae3d3b', info: '#096bb7' },
    },
    fonts: {
      heading: { family: 'Lora', weights: [500, 600, 700] },
      body: { family: 'Karla', weights: [400, 500, 700] },
    },
    radius: 4,
    shadows: 'soft',
    imageTreatment: 'warm',
    brandBound: false,
    stylesheetPath: '/design-systems/context/styles.css',
  },
  {
    id: 'darkroom',
    name: 'Darkroom',
    series: 'foundation',
    primitive: null,
    direction: 'Monochrome studio',
    palette: {
      band: 'dark',
      bg: '#141414',
      surface: '#1c1c1c',
      text: '#ededed',
      accent: '#d4ff3f',
      accent2: '#ededed',
      status: { running: '#d4ff3f', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Syne', weights: [600, 700, 800] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/darkroom/styles.css',
  },
  {
    id: 'delegate',
    name: 'Delegate',
    series: 'ainative',
    primitive: 'Multi-agent systems',
    direction: 'Supervisors & workers',
    palette: {
      band: 'dark',
      bg: '#1a1626',
      surface: '#241e33',
      text: '#f1ecff',
      accent: '#b388ff',
      accent2: '#80ffdb',
      status: { running: '#b388ff', success: '#5dc478', warning: '#ecb33b', error: '#f9837b', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Urbanist', weights: [600, 700] },
      body: { family: 'Nunito Sans', weights: [400, 600] },
    },
    radius: 12,
    shadows: 'soft',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/delegate/styles.css',
  },
  {
    id: 'drafting',
    name: 'Drafting',
    series: 'foundation',
    primitive: null,
    direction: 'Blueprint / technical',
    palette: {
      band: 'dark',
      bg: '#0e2a47',
      surface: '#123556',
      text: '#dbe9ff',
      accent: '#ffd166',
      accent2: '#8ecae6',
      status: { running: '#ffd166', success: '#73bf84', warning: '#e3b662', error: '#ea8d86', info: '#70b0f0' },
    },
    fonts: {
      heading: { family: 'Chivo Mono', weights: [500, 700] },
      body: { family: 'IBM Plex Sans', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'blueprint',
    brandBound: false,
    stylesheetPath: '/design-systems/drafting/styles.css',
  },
  {
    id: 'episode',
    name: 'Episode',
    series: 'ainative',
    primitive: 'ZeroMemory · episodic',
    direction: 'Memory over time',
    palette: {
      band: 'dark',
      bg: '#14161c',
      surface: '#1c1f27',
      text: '#e9e6df',
      accent: '#c9a227',
      accent2: '#6b9ac4',
      status: { running: '#c9a227', success: '#71c083', warning: '#e3b65f', error: '#ec8c85', info: '#6fb0f2' },
    },
    fonts: {
      heading: { family: 'Newsreader', weights: [500, 600] },
      body: { family: 'Source Sans 3', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'none',
    imageTreatment: 'sepia',
    brandBound: false,
    stylesheetPath: '/design-systems/episode/styles.css',
  },
  {
    id: 'fjord',
    name: 'Fjord',
    series: 'foundation',
    primitive: null,
    direction: 'Scandinavian',
    palette: {
      band: 'light',
      bg: '#f7f6f3',
      surface: '#ffffff',
      text: '#2c3038',
      accent: '#4a6b5a',
      accent2: '#c8a27a',
      status: { running: '#4a6b5a', success: '#3f774d', warning: '#9b7b3c', error: '#96534e', info: '#3e6c9b' },
    },
    fonts: {
      heading: { family: 'Manrope', weights: [500, 600, 700] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/fjord/styles.css',
  },
  {
    id: 'frost',
    name: 'Frost',
    series: 'foundation',
    primitive: null,
    direction: 'Glassmorphism',
    palette: {
      band: 'dark',
      bg: '#0e1424',
      surface: 'rgba(255,255,255,0.08)',
      text: '#eef2ff',
      accent: '#7aa2ff',
      accent2: '#c084fc',
      status: { running: '#7aa2ff', success: '#6fc081', warning: '#e5b65b', error: '#ee8b84', info: '#6cb0f4' },
    },
    fonts: {
      heading: { family: 'Outfit', weights: [500, 600, 700] },
      body: { family: 'DM Sans', weights: [400, 500] },
    },
    radius: 16,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/frost/styles.css',
  },
  {
    id: 'gazette',
    name: 'Gazette',
    series: 'foundation',
    primitive: null,
    direction: 'Paper / print',
    palette: {
      band: 'light',
      bg: '#efe6d3',
      surface: '#f6efe0',
      text: '#2a231c',
      accent: '#7b1e1e',
      accent2: '#3b5b3c',
      status: { running: '#7b1e1e', success: '#327a46', warning: '#a07926', error: '#9e4d48', info: '#326ca5' },
    },
    fonts: {
      heading: { family: 'Newsreader', weights: [500, 600, 700] },
      body: { family: 'Libre Franklin', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'halftone',
    brandBound: false,
    stylesheetPath: '/design-systems/gazette/styles.css',
  },
  {
    id: 'graph',
    name: 'Graph',
    series: 'ainative',
    primitive: 'Knowledge Graph',
    direction: 'Relationships & context',
    palette: {
      band: 'dark',
      bg: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      accent: '#7dd3fc',
      accent2: '#34d399',
      status: { running: '#7dd3fc', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Schibsted Grotesk', weights: [500, 600, 700] },
      body: { family: 'Schibsted Grotesk', weights: [400, 500, 600] },
    },
    radius: 12,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/graph/styles.css',
  },
  {
    id: 'guardrail',
    name: 'Guardrail',
    series: 'ainative',
    primitive: 'Production AI · guardrails',
    direction: 'Safety & permissions',
    palette: {
      band: 'dark',
      bg: '#0a0a0a',
      surface: '#151515',
      text: '#fafafa',
      accent: '#ffd60a',
      accent2: '#ff3b30',
      status: { running: '#ffd60a', success: '#57c575', warning: '#eeb22c', error: '#fd8079', info: '#62b0fe' },
    },
    fonts: {
      heading: { family: 'Archivo', weights: [700, 800] },
      body: { family: 'Archivo', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/guardrail/styles.css',
  },
  {
    id: 'harness',
    name: 'Harness',
    series: 'ainative',
    primitive: 'Agent Cloud · harness',
    direction: 'Industrial control system',
    palette: {
      band: 'light',
      bg: '#f2f3f0',
      surface: '#ffffff',
      text: '#171a17',
      accent: '#ff6a00',
      accent2: '#1b998b',
      status: { running: '#ff6a00', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Space Grotesk', weights: [500, 700] },
      body: { family: 'IBM Plex Mono', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'hard',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/harness/styles.css',
  },
  {
    id: 'kit',
    name: 'Kit',
    series: 'ainative',
    primitive: 'AIKit',
    direction: 'Interface primitives',
    palette: {
      band: 'light',
      bg: '#ffffff',
      surface: '#f9fafb',
      text: '#111827',
      accent: '#0ea5e9',
      accent2: '#10b981',
      status: { running: '#0ea5e9', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Geist', weights: [500, 600, 700] },
      body: { family: 'Geist', weights: [400, 500, 600] },
    },
    radius: 8,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/kit/styles.css',
  },
  {
    id: 'kowloon',
    name: 'Kowloon',
    series: 'foundation',
    primitive: null,
    direction: 'Cyberpunk neon',
    palette: {
      band: 'dark',
      bg: '#06080f',
      surface: '#0d1120',
      text: '#e6f7ff',
      accent: '#00f0ff',
      accent2: '#ffe600',
      status: { running: '#00f0ff', success: '#6cc180', warning: '#e6b556', error: '#f08a82', info: '#69b0f7' },
    },
    fonts: {
      heading: { family: 'Chakra Petch', weights: [600, 700] },
      body: { family: 'IBM Plex Sans', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'glow',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/kowloon/styles.css',
  },
  {
    id: 'latent',
    name: 'Latent',
    series: 'ainative',
    primitive: 'ZeroDB · vectors',
    direction: 'Vector space',
    palette: {
      band: 'dark',
      bg: '#0b0a1f',
      surface: '#15142e',
      text: '#ecebff',
      accent: '#8b8cff',
      accent2: '#ff7ac3',
      status: { running: '#8b8cff', success: '#61c37a', warning: '#ebb442', error: '#f7847d', info: '#62b0fe' },
    },
    fonts: {
      heading: { family: 'Sora', weights: [500, 600, 700] },
      body: { family: 'DM Sans', weights: [400, 500] },
    },
    radius: 12,
    shadows: 'glow',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/latent/styles.css',
  },
  {
    id: 'loop',
    name: 'Loop',
    series: 'ainative',
    primitive: 'Agents · observe/reason/decide/act',
    direction: 'The agent loop',
    palette: {
      band: 'dark',
      bg: '#0f1424',
      surface: '#171d33',
      text: '#eef1fb',
      accent: '#5b7cfa',
      accent2: '#ff5fa2',
      status: { running: '#5b7cfa', success: '#4fc771', warning: '#f1b111', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Plus Jakarta Sans', weights: [600, 700, 800] },
      body: { family: 'Plus Jakarta Sans', weights: [400, 500, 600] },
    },
    radius: 999,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/loop/styles.css',
  },
  {
    id: 'marquee',
    name: 'Marquee',
    series: 'foundation',
    primitive: null,
    direction: 'Art deco',
    palette: {
      band: 'dark',
      bg: '#0f1a1c',
      surface: '#162527',
      text: '#f0e6c8',
      accent: '#d4af37',
      accent2: '#8fb3a9',
      status: { running: '#d4af37', success: '#71c083', warning: '#e4b65f', error: '#ec8c85', info: '#6eb0f2' },
    },
    fonts: {
      heading: { family: 'Poiret One', weights: [400] },
      body: { family: 'Josefin Sans', weights: [400, 600] },
    },
    radius: 0,
    shadows: 'soft',
    imageTreatment: 'sepia',
    brandBound: false,
    stylesheetPath: '/design-systems/marquee/styles.css',
  },
  {
    id: 'marshmallow',
    name: 'Marshmallow',
    series: 'foundation',
    primitive: null,
    direction: 'Pastel soft UI',
    palette: {
      band: 'light',
      bg: '#f6f1fb',
      surface: '#fbf8fe',
      text: '#3a3350',
      accent: '#7c5cd6',
      accent2: '#e37fb1',
      status: { running: '#7c5cd6', success: '#087e39', warning: '#a4780c', error: '#b03b39', info: '#076bb8' },
    },
    fonts: {
      heading: { family: 'Quicksand', weights: [600, 700] },
      body: { family: 'Nunito', weights: [400, 600] },
    },
    radius: 20,
    shadows: 'neu',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/marshmallow/styles.css',
  },
  {
    id: 'merge',
    name: 'Merge',
    series: 'ainative',
    primitive: 'Branching, chaining, merging',
    direction: 'Execution graphs',
    palette: {
      band: 'light',
      bg: '#fafafa',
      surface: '#ffffff',
      text: '#18181b',
      accent: '#16a34a',
      accent2: '#9333ea',
      status: { running: '#16a34a', success: '#087e39', warning: '#a4780d', error: '#ad3f3c', info: '#076bb8' },
    },
    fonts: {
      heading: { family: 'Rubik', weights: [500, 600, 700] },
      body: { family: 'Rubik', weights: [400, 500] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/merge/styles.css',
  },
  {
    id: 'orbit',
    name: 'Orbit',
    series: 'foundation',
    primitive: null,
    direction: 'Space / sci-fi',
    palette: {
      band: 'dark',
      bg: '#050810',
      surface: '#0c1220',
      text: '#e8ecf5',
      accent: '#a78bfa',
      accent2: '#22d3ee',
      status: { running: '#a78bfa', success: '#65c27c', warning: '#e9b44a', error: '#f4867f', info: '#63b0fd' },
    },
    fonts: {
      heading: { family: 'Space Grotesk', weights: [500, 700] },
      body: { family: 'Space Grotesk', weights: [400, 500, 700] },
    },
    radius: 4,
    shadows: 'glow',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/orbit/styles.css',
  },
  {
    id: 'pulse',
    name: 'Pulse',
    series: 'ainative',
    primitive: 'Inference for Agents',
    direction: 'Inference infrastructure',
    palette: {
      band: 'light',
      bg: '#ffffff',
      surface: '#f3f4f6',
      text: '#111827',
      accent: '#0ea5e9',
      accent2: '#10b981',
      status: { running: '#0ea5e9', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Hanken Grotesk', weights: [500, 600, 700] },
      body: { family: 'Hanken Grotesk', weights: [400, 500, 600] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/pulse/styles.css',
  },
  {
    id: 'raster',
    name: 'Raster',
    series: 'foundation',
    primitive: null,
    direction: 'Swiss / editorial',
    palette: {
      band: 'light',
      bg: '#fbfbf9',
      surface: '#f0f0ec',
      text: '#141414',
      accent: '#0b3d91',
      accent2: '#141414',
      status: { running: '#0b3d91', success: '#227c3f', warning: '#a47807', error: '#a54743', info: '#236cae' },
    },
    fonts: {
      heading: { family: 'Instrument Sans', weights: [500, 600, 700] },
      body: { family: 'Instrument Sans', weights: [400, 500, 600, 700] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/raster/styles.css',
  },
  {
    id: 'recall',
    name: 'Recall',
    series: 'ainative',
    primitive: 'ZeroMemory',
    direction: 'Persistent agent memory',
    palette: {
      band: 'light',
      bg: '#fafaf9',
      surface: '#ffffff',
      text: '#1f2937',
      accent: '#0369a1',
      accent2: '#f59e0b',
      status: { running: '#0369a1', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Figtree', weights: [500, 600, 700] },
      body: { family: 'Figtree', weights: [400, 500, 600] },
    },
    radius: 10,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/recall/styles.css',
  },
  {
    id: 'router',
    name: 'Router',
    series: 'ainative',
    primitive: 'Models API',
    direction: 'Model access & routing',
    palette: {
      band: 'dark',
      bg: '#1f2937',
      surface: '#111827',
      text: '#f9fafb',
      accent: '#0ea5e9',
      accent2: '#f59e0b',
      status: { running: '#0ea5e9', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Onest', weights: [500, 600, 700] },
      body: { family: 'Onest', weights: [400, 500, 600] },
    },
    radius: 999,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/router/styles.css',
  },
  {
    id: 'signal',
    name: 'Signal',
    series: 'ainative',
    primitive: 'Agent Cloud · observability',
    direction: 'Telemetry & tracing',
    palette: {
      band: 'dark',
      bg: '#050b0f',
      surface: '#0b151c',
      text: '#d7f3ff',
      accent: '#00e0c6',
      accent2: '#ff9f1c',
      status: { running: '#00e0c6', success: '#6cc180', warning: '#e6b557', error: '#ef8a82', info: '#6ab0f6' },
    },
    fonts: {
      heading: { family: 'Chivo Mono', weights: [500, 700] },
      body: { family: 'Chivo', weights: [400, 500, 700] },
    },
    radius: 0,
    shadows: 'glow',
    imageTreatment: 'phosphor',
    brandBound: false,
    stylesheetPath: '/design-systems/signal/styles.css',
  },
  {
    id: 'sketchbook',
    name: 'Sketchbook',
    series: 'foundation',
    primitive: null,
    direction: 'Handmade / sketch',
    palette: {
      band: 'light',
      bg: '#fdfbf5',
      surface: '#ffffff',
      text: '#2b2b2b',
      accent: '#ff6b35',
      accent2: '#3aa6a0',
      status: { running: '#ff6b35', success: '#0b7e3a', warning: '#a57700', error: '#b43535', info: '#096bb7' },
    },
    fonts: {
      heading: { family: 'Architects Daughter', weights: [400] },
      body: { family: 'Nunito Sans', weights: [400, 600, 700] },
    },
    radius: 8,
    shadows: 'none',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/sketchbook/styles.css',
  },
  {
    id: 'stack',
    name: 'Stack',
    series: 'ainative',
    primitive: 'The nine-layer stack',
    direction: 'Architecture diagram',
    palette: {
      band: 'light',
      bg: '#eef0f2',
      surface: '#ffffff',
      text: '#0f172a',
      accent: '#0f172a',
      accent2: '#f97316',
      status: { running: '#0f172a', success: '#3f774d', warning: '#9b7b3c', error: '#96534e', info: '#3e6c9b' },
    },
    fonts: {
      heading: { family: 'Bricolage Grotesque', weights: [600, 700, 800] },
      body: { family: 'Archivo', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/stack/styles.css',
  },
  {
    id: 'vinyl',
    name: 'Vinyl',
    series: 'foundation',
    primitive: null,
    direction: 'Seventies record sleeve',
    palette: {
      band: 'dark',
      bg: '#1a1410',
      surface: '#241c16',
      text: '#f4e7cf',
      accent: '#e07a1f',
      accent2: '#b8a638',
      status: { running: '#e07a1f', success: '#66c27d', warning: '#e8b54c', error: '#f4877f', info: '#64b0fc' },
    },
    fonts: {
      heading: { family: 'Abril Fatface', weights: [400] },
      body: { family: 'Karla', weights: [400, 500, 700] },
    },
    radius: 6,
    shadows: 'none',
    imageTreatment: 'warm',
    brandBound: false,
    stylesheetPath: '/design-systems/vinyl/styles.css',
  },
  {
    id: 'washi',
    name: 'Washi',
    series: 'foundation',
    primitive: null,
    direction: 'Japanese minimal',
    palette: {
      band: 'light',
      bg: '#faf8f4',
      surface: '#f1eee7',
      text: '#2b2a28',
      accent: '#b23a2f',
      accent2: '#5a6b5e',
      status: { running: '#b23a2f', success: '#177d3c', warning: '#a47806', error: '#a84440', info: '#1a6cb2' },
    },
    fonts: {
      heading: { family: 'Shippori Mincho', weights: [500, 700] },
      body: { family: 'Zen Kaku Gothic New', weights: [400, 500, 700] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/washi/styles.css',
  },
  {
    id: 'werkstatt',
    name: 'Werkstatt',
    series: 'foundation',
    primitive: null,
    direction: 'Bauhaus',
    palette: {
      band: 'light',
      bg: '#f4efe6',
      surface: '#ebe4d6',
      text: '#1b1b1b',
      accent: '#d9261c',
      accent2: '#f2b705',
      status: { running: '#d9261c', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Josefin Sans', weights: [600, 700] },
      body: { family: 'Work Sans', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/werkstatt/styles.css',
  },
  {
    id: 'zero',
    name: 'Zero',
    series: 'ainative',
    primitive: 'ZeroDB',
    direction: 'AI-native data layer',
    palette: {
      band: 'light',
      bg: '#f9fafb',
      surface: '#ffffff',
      text: '#111827',
      accent: '#0284c7',
      accent2: '#3b82f6',
      status: { running: '#0284c7', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Public Sans', weights: [500, 600, 700] },
      body: { family: 'Public Sans', weights: [400, 500, 600] },
    },
    radius: 4,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/zero/styles.css',
  },
]

export function getDesignSystem(id: string): DesignSystem | undefined {
  return DESIGN_SYSTEMS.find((s) => s.id === id)
}
