/**
 * Design System Picker — the MVP catalog of 6 systems (#590).
 *
 * Data below is transcribed exactly from the real theme.json files in the
 * source drop (`~/Downloads/Design systems for builder product/systems/`),
 * except Modernist, whose values come from the LIVE codebase (app/modernist.css)
 * — Modernist is Builder's own existing chrome, already confirmed identical to
 * its counterpart export in that same drop's `_ds/modernist-<uuid>/` bundle.
 *
 * Do not hand-edit values here without re-checking the source file — this
 * catalog is the single source of truth for both the picker UI (#591) and
 * the codegen prompt injection (#592).
 */

import type { DesignSystem } from './types'

export const DESIGN_SYSTEMS: DesignSystem[] = [
  {
    id: 'modernist',
    name: 'Modernist',
    series: 'builder',
    primitive: null,
    direction: "Builder's own current look — brutalist editorial, machine-speech UI",
    palette: {
      band: 'light',
      bg: '#f3f2f2',
      surface: '#e9e7e7',
      text: '#201e1d',
      accent: '#ec3013',
      accent2: '#d7d3d3',
      // Modernist has no per-status semantic palette in the live codebase —
      // omitted rather than fabricated (see types.ts's doc comment).
    },
    fonts: {
      heading: { family: 'Archivo', weights: [400, 500, 600, 700, 800] },
      body: { family: 'Archivo', weights: [400, 500, 600, 700] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: null,
  },
  {
    id: 'noir',
    name: 'Noir',
    series: 'foundation',
    primitive: null,
    direction: 'Luxury fashion',
    palette: {
      band: 'dark',
      bg: '#101010',
      surface: '#181818',
      text: '#f2efe9',
      accent: '#c9b27c',
      accent2: '#f2efe9',
      status: { running: '#c9b27c', success: '#81bb8d', warning: '#dbb879', error: '#de958e', info: '#7fafe2' },
    },
    fonts: {
      heading: { family: 'Cormorant', weights: [300, 400, 500] },
      body: { family: 'Jost', weights: [300, 400, 500] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/noir/styles.css',
  },
  {
    id: 'crayon',
    name: 'Crayon',
    series: 'foundation',
    primitive: null,
    direction: 'Playful / toy',
    palette: {
      band: 'light',
      bg: '#fff8ec',
      surface: '#ffffff',
      text: '#2a1f3d',
      accent: '#ff5c8a',
      accent2: '#ffb703',
      status: { running: '#ff5c8a', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Fredoka', weights: [600, 700] },
      body: { family: 'Nunito', weights: [400, 600, 700] },
    },
    radius: 16,
    shadows: 'hard',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/crayon/styles.css',
  },
  {
    id: 'cody',
    name: 'Cody',
    series: 'ainative',
    primitive: 'Cody (CTO agent)',
    direction: 'Pair-programming agent',
    palette: {
      band: 'dark',
      bg: '#0b1220',
      surface: '#111827',
      text: '#e5e7eb',
      accent: '#7dd3fc',
      accent2: '#f59e0b',
      status: { running: '#7dd3fc', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Geist Mono', weights: [500, 700] },
      body: { family: 'Geist', weights: [400, 500, 600] },
    },
    radius: 4,
    shadows: 'none',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/cody/styles.css',
  },
  {
    id: 'outrun',
    name: 'Outrun',
    series: 'foundation',
    primitive: null,
    direction: 'Neo-retro 80s',
    palette: {
      band: 'dark',
      bg: '#140a2b',
      surface: '#1e1040',
      text: '#fbeaff',
      accent: '#ff2fa0',
      accent2: '#2ee6ff',
      status: { running: '#ff2fa0', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Orbitron', weights: [500, 700, 900] },
      body: { family: 'Exo 2', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'glow',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/outrun/styles.css',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    series: 'ainative',
    primitive: 'AI COGS',
    direction: 'Economics & cost accounting',
    palette: {
      band: 'light',
      bg: '#fbfaf6',
      surface: '#f3f1ea',
      text: '#1e2a1f',
      accent: '#1f6f43',
      accent2: '#b8860b',
      status: { running: '#1f6f43', success: '#3f774d', warning: '#9b7b3c', error: '#96534e', info: '#3e6c9b' },
    },
    fonts: {
      heading: { family: 'Libre Franklin', weights: [500, 600, 700] },
      body: { family: 'JetBrains Mono', weights: [400, 500] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'halftone',
    brandBound: false,
    stylesheetPath: '/design-systems/ledger/styles.css',
  },
  {
    id: 'approval',
    name: 'Approval',
    series: 'ainative',
    primitive: 'AIKit · human-in-the-loop',
    direction: 'Human-in-the-loop',
    palette: {
      band: 'light',
      bg: '#ffffff',
      surface: '#f5f7fb',
      text: '#14213d',
      accent: '#e63946',
      accent2: '#2a9d8f',
      status: { running: '#e63946', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Manrope', weights: [600, 700, 800] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 4,
    shadows: 'soft',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/approval/styles.css',
  },
  {
    id: 'chrome',
    name: 'Chrome',
    series: 'foundation',
    primitive: null,
    direction: 'Y2K',
    palette: {
      band: 'light',
      bg: '#e9edf5',
      surface: '#f7f9fd',
      text: '#0b1a3a',
      accent: '#0057ff',
      accent2: '#ff5ad1',
      status: { running: '#0057ff', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Unbounded', weights: [500, 700] },
      body: { family: 'Kumbh Sans', weights: [400, 500, 700] },
    },
    radius: 999,
    shadows: 'soft',
    imageTreatment: 'cool',
    brandBound: false,
    stylesheetPath: '/design-systems/chrome/styles.css',
  },
  {
    id: 'cloud',
    name: 'Cloud',
    series: 'ainative',
    primitive: 'Agent Cloud',
    direction: 'Agent runtime & orchestration',
    palette: {
      band: 'dark',
      bg: '#111827',
      surface: '#1f2937',
      text: '#f9fafb',
      accent: '#38bdf8',
      accent2: '#10b981',
      status: { running: '#38bdf8', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'IBM Plex Sans', weights: [500, 600] },
      body: { family: 'IBM Plex Sans', weights: [400, 500, 600] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/cloud/styles.css',
  },
  {
    id: 'concrete',
    name: 'Concrete',
    series: 'foundation',
    primitive: null,
    direction: 'Brutalist',
    palette: {
      band: 'light',
      bg: '#e9e7e2',
      surface: '#dfdcd5',
      text: '#121212',
      accent: '#1f1fff',
      accent2: '#121212',
      status: { running: '#1f1fff', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Space Grotesk', weights: [500, 700] },
      body: { family: 'IBM Plex Mono', weights: [400, 600] },
    },
    radius: 0,
    shadows: 'hard',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/concrete/styles.css',
  },
  {
    id: 'console',
    name: 'Console',
    series: 'foundation',
    primitive: null,
    direction: 'Terminal / hacker',
    palette: {
      band: 'dark',
      bg: '#0a0d0a',
      surface: '#111711',
      text: '#c9f2c2',
      accent: '#3dff6e',
      accent2: '#ffd23d',
      status: { running: '#3dff6e', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'JetBrains Mono', weights: [500, 700] },
      body: { family: 'JetBrains Mono', weights: [400, 500, 700] },
    },
    radius: 0,
    shadows: 'glow',
    imageTreatment: 'phosphor',
    brandBound: false,
    stylesheetPath: '/design-systems/console/styles.css',
  },
  {
    id: 'context',
    name: 'Context',
    series: 'ainative',
    primitive: 'Memory + context layer',
    direction: 'The desk and the cabinet',
    palette: {
      band: 'light',
      bg: '#f7f1e8',
      surface: '#fffaf2',
      text: '#2c2418',
      accent: '#c2410c',
      accent2: '#4a7c59',
      status: { running: '#c2410c', success: '#0a7e3a', warning: '#a4780f', error: '#ae3d3b', info: '#096bb7' },
    },
    fonts: {
      heading: { family: 'Lora', weights: [500, 600, 700] },
      body: { family: 'Karla', weights: [400, 500, 700] },
    },
    radius: 4,
    shadows: 'soft',
    imageTreatment: 'warm',
    brandBound: false,
    stylesheetPath: '/design-systems/context/styles.css',
  },
  {
    id: 'darkroom',
    name: 'Darkroom',
    series: 'foundation',
    primitive: null,
    direction: 'Monochrome studio',
    palette: {
      band: 'dark',
      bg: '#141414',
      surface: '#1c1c1c',
      text: '#ededed',
      accent: '#d4ff3f',
      accent2: '#ededed',
      status: { running: '#d4ff3f', success: '#47c86e', warning: '#f1b112', error: '#ff7e77', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Syne', weights: [600, 700, 800] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'none',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/darkroom/styles.css',
  },
  {
    id: 'delegate',
    name: 'Delegate',
    series: 'ainative',
    primitive: 'Multi-agent systems',
    direction: 'Supervisors & workers',
    palette: {
      band: 'dark',
      bg: '#1a1626',
      surface: '#241e33',
      text: '#f1ecff',
      accent: '#b388ff',
      accent2: '#80ffdb',
      status: { running: '#b388ff', success: '#5dc478', warning: '#ecb33b', error: '#f9837b', info: '#61b0fe' },
    },
    fonts: {
      heading: { family: 'Urbanist', weights: [600, 700] },
      body: { family: 'Nunito Sans', weights: [400, 600] },
    },
    radius: 12,
    shadows: 'soft',
    imageTreatment: 'duotone',
    brandBound: false,
    stylesheetPath: '/design-systems/delegate/styles.css',
  },
  {
    id: 'drafting',
    name: 'Drafting',
    series: 'foundation',
    primitive: null,
    direction: 'Blueprint / technical',
    palette: {
      band: 'dark',
      bg: '#0e2a47',
      surface: '#123556',
      text: '#dbe9ff',
      accent: '#ffd166',
      accent2: '#8ecae6',
      status: { running: '#ffd166', success: '#73bf84', warning: '#e3b662', error: '#ea8d86', info: '#70b0f0' },
    },
    fonts: {
      heading: { family: 'Chivo Mono', weights: [500, 700] },
      body: { family: 'IBM Plex Sans', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'blueprint',
    brandBound: false,
    stylesheetPath: '/design-systems/drafting/styles.css',
  },
  {
    id: 'episode',
    name: 'Episode',
    series: 'ainative',
    primitive: 'ZeroMemory · episodic',
    direction: 'Memory over time',
    palette: {
      band: 'dark',
      bg: '#14161c',
      surface: '#1c1f27',
      text: '#e9e6df',
      accent: '#c9a227',
      accent2: '#6b9ac4',
      status: { running: '#c9a227', success: '#71c083', warning: '#e3b65f', error: '#ec8c85', info: '#6fb0f2' },
    },
    fonts: {
      heading: { family: 'Newsreader', weights: [500, 600] },
      body: { family: 'Source Sans 3', weights: [400, 500, 600] },
    },
    radius: 2,
    shadows: 'none',
    imageTreatment: 'sepia',
    brandBound: false,
    stylesheetPath: '/design-systems/episode/styles.css',
  },
  {
    id: 'fjord',
    name: 'Fjord',
    series: 'foundation',
    primitive: null,
    direction: 'Scandinavian',
    palette: {
      band: 'light',
      bg: '#f7f6f3',
      surface: '#ffffff',
      text: '#2c3038',
      accent: '#4a6b5a',
      accent2: '#c8a27a',
      status: { running: '#4a6b5a', success: '#3f774d', warning: '#9b7b3c', error: '#96534e', info: '#3e6c9b' },
    },
    fonts: {
      heading: { family: 'Manrope', weights: [500, 600, 700] },
      body: { family: 'Manrope', weights: [400, 500, 600] },
    },
    radius: 6,
    shadows: 'soft',
    imageTreatment: 'grayscale',
    brandBound: false,
    stylesheetPath: '/design-systems/fjord/styles.css',
  },
  {
    id: 'frost',
    name: 'Frost',
    series: 'foundation',
    primitive: null,
    direction: 'Glassmorphism',
    palette: {
      band: 'dark',
      bg: '#0e1424',
      surface: 'rgba(255,255,255,0.08)',
      text: '#eef2ff',
      accent: '#7aa2ff',
      accent2: '#c084fc',
      status: { running: '#7aa2ff', success: '#6fc081', warning: '#e5b65b', error: '#ee8b84', info: '#6cb0f4' },
    },
    fonts: {
      heading: { family: 'Outfit', weights: [500, 600, 700] },
      body: { family: 'DM Sans', weights: [400, 500] },
    },
    radius: 16,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: false,
    stylesheetPath: '/design-systems/frost/styles.css',
  },
  {
    id: 'gazette',
    name: 'Gazette',
    series: 'foundation',
    primitive: null,
    direction: 'Paper / print',
    palette: {
      band: 'light',
      bg: '#efe6d3',
      surface: '#f6efe0',
      text: '#2a231c',
      accent: '#7b1e1e',
      accent2: '#3b5b3c',
      status: { running: '#7b1e1e', success: '#327a46', warning: '#a07926', error: '#9e4d48', info: '#326ca5' },
    },
    fonts: {
      heading: { family: 'Newsreader', weights: [500, 600, 700] },
      body: { family: 'Libre Franklin', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'halftone',
    brandBound: false,
    stylesheetPath: '/design-systems/gazette/styles.css',
  },
  {
    id: 'graph',
    name: 'Graph',
    series: 'ainative',
    primitive: 'Knowledge Graph',
    direction: 'Relationships & context',
    palette: {
      band: 'dark',
      bg: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      accent: '#7dd3fc',
      accent2: '#34d399',
      status: { running: '#7dd3fc', success: '#10b981', warning: '#f59e0b', error: '#ef4444', info: '#3b82f6' },
    },
    fonts: {
      heading: { family: 'Schibsted Grotesk', weights: [500, 600, 700] },
      body: { family: 'Schibsted Grotesk', weights: [400, 500, 600] },
    },
    radius: 12,
    shadows: 'soft',
    imageTreatment: 'none',
    brandBound: true,
    stylesheetPath: '/design-systems/graph/styles.css',
  },
  {
    id: 'guardrail',
    name: 'Guardrail',
    series: 'ainative',
    primitive: 'Production AI · guardrails',
    direction: 'Safety & permissions',
    palette: {
      band: 'dark',
      bg: '#0a0a0a',
      surface: '#151515',
      text: '#fafafa',
      accent: '#ffd60a',
      accent2: '#ff3b30',
      status: { running: '#ffd60a', success: '#57c575', warning: '#eeb22c', error: '#fd8079', info: '#62b0fe' },
    },
    fonts: {
      heading: { family: 'Archivo', weights: [700, 800] },
      body: { family: 'Archivo', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'none',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/guardrail/styles.css',
  },
  {
    id: 'harness',
    name: 'Harness',
    series: 'ainative',
    primitive: 'Agent Cloud · harness',
    direction: 'Industrial control system',
    palette: {
      band: 'light',
      bg: '#f2f3f0',
      surface: '#ffffff',
      text: '#171a17',
      accent: '#ff6a00',
      accent2: '#1b998b',
      status: { running: '#ff6a00', success: '#047e39', warning: '#a47807', error: '#b63132', info: '#036bb9' },
    },
    fonts: {
      heading: { family: 'Space Grotesk', weights: [500, 700] },
      body: { family: 'IBM Plex Mono', weights: [400, 500, 600] },
    },
    radius: 0,
    shadows: 'hard',
    imageTreatment: 'contrast',
    brandBound: false,
    stylesheetPath: '/design-systems/harness/styles.css',
  },
]

export function getDesignSystem(id: string): DesignSystem | undefined {
  return DESIGN_SYSTEMS.find((s) => s.id === id)
}
